# Generated by Django 5.1.4 on 2026-05-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0003_workshopownerprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('billing_interval', models.CharField(choices=[('month', 'Mensual'), ('year', 'Anual')], default='month', max_length=10)),
                ('max_technicians', models.PositiveIntegerField(default=5)),
                ('max_monthly_incidents', models.PositiveIntegerField(default=100, help_text='Límite orientativo de incidentes atendidos por mes')),
                ('features', models.JSONField(blank=True, default=list)),
                ('stripe_product_id', models.CharField(blank=True, max_length=120)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workshop_subscription_plans',
                'ordering': ['sort_order', 'price_amount'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopOwnerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('active', 'Activa'), ('past_due', 'Pago atrasado'), ('canceled', 'Cancelada'), ('incomplete', 'Incompleta')], default='pending', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.workshopownerprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.workshopsubscriptionplan')),
            ],
            options={
                'db_table': 'workshop_owner_subscriptions',
            },
        ),
    ]
