# Generated by Django 5.1.4 on 2026-04-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField()),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=40)),
                ('vehicle_type', models.CharField(choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('truck', 'Camión'), ('van', 'Camioneta'), ('bus', 'Bus')], max_length=20)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.clientprofile')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
