# Generated by Django 5.1.4 on 2026-04-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('workshop_owner', 'Dueño de Taller'), ('client', 'Cliente'), ('technician', 'Técnico')], default='client', max_length=20),
        ),
    ]
