# Generated by Django 5.1.4 on 2026-05-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_technician_role_and_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopownerprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
