# Generated by Django 5.1.4 on 2026-04-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offered', 'Ofrecida al taller'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('in_route', 'Técnico en camino'), ('arrived', 'Técnico llegó'), ('in_service', 'En servicio'), ('completed', 'Completada')], default='offered', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_arrival_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('service_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.incident')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='workshops.technician')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workshops.workshop')),
            ],
            options={
                'db_table': 'assignments',
                'indexes': [models.Index(fields=['status'], name='assignments_status_7bfe3b_idx'), models.Index(fields=['incident'], name='assignments_inciden_6f88b7_idx')],
            },
        ),
    ]
