# Generated by Django 5.1.4 on 2026-04-04 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando con IA'), ('waiting_workshop', 'Esperando taller'), ('assigned', 'Taller asignado'), ('in_progress', 'En atención'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=30)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20, null=True)),
                ('incident_type', models.CharField(choices=[('battery', 'Batería'), ('tire', 'Llanta'), ('accident', 'Choque / Accidente'), ('engine', 'Motor'), ('locksmith', 'Llaves / Cerrajería'), ('overheating', 'Sobrecalentamiento'), ('other', 'Otro'), ('uncertain', 'Incierto')], default='uncertain', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address_text', models.TextField(blank=True)),
                ('ai_transcription', models.TextField(blank=True)),
                ('ai_classification_raw', models.JSONField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='users.clientprofile')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('image', 'Imagen'), ('audio', 'Audio'), ('text', 'Texto adicional')], max_length=10)),
                ('file', models.FileField(upload_to='incidents/files/%Y/%m/%d/')),
                ('transcription', models.TextField(blank=True)),
                ('transcription_done', models.BooleanField(default=False)),
                ('image_analysis', models.JSONField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='incidents.incident')),
            ],
            options={
                'db_table': 'evidences',
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando con IA'), ('waiting_workshop', 'Esperando taller'), ('assigned', 'Taller asignado'), ('in_progress', 'En atención'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], max_length=30)),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('analyzing', 'Analizando con IA'), ('waiting_workshop', 'Esperando taller'), ('assigned', 'Taller asignado'), ('in_progress', 'En atención'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incident')),
            ],
            options={
                'db_table': 'incident_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_status_9db31b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['priority'], name='incidents_priorit_672f71_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='incidents_created_bc994b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['client'], name='incidents_client__6d6c87_idx'),
        ),
    ]
