# Generated by Django 5.1.4 on 2026-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type_web'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webpushsubscription',
            new_name='web_push_su_user_id_057144_idx',
            old_name='web_push_user_active_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('incident_created', 'Incidente creado'), ('workshop_assigned', 'Taller asignado'), ('technician_assigned', 'Orden asignada al técnico'), ('technician_nearby', 'Técnico cerca de tu ubicación'), ('technician_in_route', 'Técnico en camino'), ('service_completed', 'Servicio completado'), ('payment_required', 'Pago requerido'), ('payment_confirmed', 'Pago confirmado'), ('new_request', 'Nueva solicitud (taller)'), ('status_updated', 'Estado actualizado'), ('new_rating', 'Nueva calificación (taller)'), ('workshop_verified', 'Taller verificado (panel)'), ('workshop_pending_review', 'Taller pendiente de revisión (admin)')], max_length=40),
        ),
    ]
